import { v4 as uuidv4 } from 'uuid';

export const items =  [
    {
      id: uuidv4(),
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price:89999,
      quantity : 1,
      instock:"yes",
      instock_bullian:true,
    },
    {
      id: uuidv4(),
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: '(Refurbished) Xiaomi Mi Notebook Ultra Max- Intel 11th Gen i5-11320H Thin & Light (Intel Iris Xe Graphics/16GB DDR4 RAM/512GB SSD/15.6" inch 3.2K Resolution/Win 11 & Office’21/Fingerprint Sensor/1.7Kg) ',
      price: 49999,
      quantity : 1,
      instock:"yes",
      instock_bullian:true,
    },
    {
      id: uuidv4(),
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| Powered by HyperOS |144Hz Refresh Rate| 8GB, 256GB| 2.8K+ Display (11-inch/27.81cm) Tablet| Dolby Vision Atmos| Quad Speakers| Wi-Fi| Gray',
      price: 29999,
      quantity : 1,
      instock:"yes",
      instock_bullian:true,
    },
    {
      id: uuidv4(),
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: 79999,
      quantity : 1,
      instock:"yes",
      instock_bullian:true,
    },
    {
      id: uuidv4(),
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: 19999,
      quantity : 1,
      instock:"no",
      instock_bullian:false,
    },
    {
      id: uuidv4(),
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: 69999,
      quantity : 1,
      instock:"yes",
      instock_bullian:true,
    },
    {
      id: uuidv4(),
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: 29999,
      quantity : 1,
      instock:"no",
      instock_bullian:false,
    },
    {
      id: uuidv4(),
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: 49999,
      quantity : 1,
      instock:"no",
      instock_bullian:false,
    },
    {
      id:uuidv4(),
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: 89999,
      quantity : 1,
      instock:"no",
      instock_bullian:false,
    },


  ]